/**
 * Commands and arguments for providing completions.
 */
export const COMMANDS = new Map<string, string[]>([
  ["%include", []],
  ["%ksappend", []],
  ["authselect", []],
  ["autopart", [
    "--encrypted",
    "--passphrase ${1:passphrase}",
    "--escrowcert ${1:cert_url}",
    "--backuppassphrase",
    "--nolvm",
    "--type ${1|lvm,btrfs,plain,partition,thinp|}",
    "--cipher ${1:cipher}",
    "--fstype ${1:fstype}",
    "--nohome",
    "--noboot",
    "--noswap",
    "--luks-version ${1:luks_version}",
    "--pbkdf ${1:pbkdf}",
    "--pbkdf-memory ${1:pbkdf_memory}",
    "--pbkdf-time ${1:pbkdf_time}",
    "--pbkdf-iterations ${1|pbkdf_iterations}",
  ]],
  ["bootloader", [
    "--append ${1:appendline}",
    "--location ${1|mbr,partition,none,boot|}",
    "--password ${1:password}",
    "--driveorder ${1:drive_order}",
    "--timeout ${1:timeout}",
    "--default ${1:default}",
    "--iscrypted",
    "--md5pass ${1:md5pass}",
    "--boot-drive ${1:boot_drive}",
    "--leavebootorder",
    "--extlinux",
    "--disabled",
    "--nombr",
  ]],
  ["cdrom", []],
  ["clearpart", [
    "--all",
    "--initlabel",
    "--linux",
    "--none",
    "--disklabel ${1:disk_label}",
    "--drives ${1:drives}",
    "--list ${1:devices}",
    "--cdl",
  ]],
  ["cmdline", []],
  ["driverdisk", [
    "UUID=${1:uuid}",
    "LABEL=${1:label}",
    "--source ${1:source}",
    "--biospart ${1:biospart}",
  ]],
  ["eula", [
    "--agreed",
  ]],
  ["fcoe", [
    "--nic ${1:nic}",
    "--dcb",
    "--autovlan",
  ]],
  ["firewall", [
    "--disable",
    "--enable",
    "--port ${1:ports}",
    "--trust ${1:trusts}",
    "--service ${1:services}",
    "--ftp",
    "--http",
    "--smtp",
    "--ssh",
    "--remove-service ${1:remove_services}",
    "--use-system-defaults",
  ]],
  ["firstboot", [
    "--disable",
    "--enable",
    "--reconfig",
  ]],
  ["graphical", [
    "--non-interactive",
  ]],
  ["group", []],
  ["halt", [
    "--eject",
    "--kexec",
  ]],
  ["harddrive", [
    "--dir ${1:dir}",
    "--partition ${1:partition}",
  ]],
  ["ignoredisk", [
    "--drives ${1:ignore_disk}",
    "--only-use ${1:only_use}",
  ]],
  ["iscsi", [
    "--target ${1:target}",
    "--ipaddr ${1:ipaddr}",
    "--port ${1:port}",
    "--user ${1:user}",
    "--password ${1:password}",
    "--reverse-user ${1:user_in}",
    "--reverse-password ${1:password_in}",
    "--iface ${1:iface}",
  ]],
  ["iscsiname", []],
  ["keyboard", [
    "--vckeymap ${1:keymap}",
    "--xlayouts ${1:layouts}",
    "--switch ${1:switch_options}",
  ]],
  ["lang", [
    "--addsupport ${1:locale}",
  ]],
  ["liveimg", [
    "--url ${1:url}",
    "--proxy ${1:proxy_url}",
    "--noverifyssl",
    "--checksum ${1:sha256}",
  ]],
  ["logging", [
    "--host ${1:host}",
    "--port ${1:port}",
  ]],
  ["logvol", [
    "--fstype ${1:fstype}",
    "--grow",
    "--maxsize ${1:maxsizemb}",
    "--name ${1:name}",
    "--noformat",
    "--percent ${1:percent}",
    "--recommended",
    "--size ${1:size}",
    "--useexisting",
    "--vgname ${1:vgname}",
    "--fsoptions ${1:fsopts}",
    "--fsprofile ${1:fsprofile}",
    "--encrypted",
    "--passphrase ${1:passphrase}",
    "--escrowcert ${1:cert_url}",
    "--backuppassphrase",
    "--label ${1:label}",
    "--resize",
    "--hibernation",
    "--cipher ${1:cipher}",
    "--thinpool",
    "--thin",
    "--poolname ${1:pool_name}",
    "--chunksize ${1:chunk_size}",
    "--metadatasize ${1:metadata_size}",
    "--profile ${1:profile}",
    "--cachesize ${1:cache_size}",
    "--cachemode ${1:cache_mode}",
    "--cachepvs ${1:cache_pvs}",
    "--mkfsoptions ${1:mkfsopts}",
    "--luks-version ${1:luks_version}",
    "--pbkdf ${1:pbkdf}",
    "--pbkdf-memory ${1:pbkdf_memory}",
    "--pbkdf-time ${1:pbkdf_time}",
    "--pbkdf-iterations ${1:pbkdf_iterations}",
  ]],
  ["mediacheck", []],
  ["module", [
    "--name ${1:module_name}",
    "--stream ${1:module_stream_name}",
    "--disable",
  ]],
  ["mount", [
    "--reformat ${1:reformat}",
    "--mkfsoptions ${1:mkfs_opts}",
    "--mountoptions ${1:mount_opts}",
  ]],
  ["network", [
    "--bootproto ${1|dhcp,bootp,static,query,ibft|}",
    "--dhcpclass ${1:dhcpclass}",
    "--device ${1:device}",
    "--essid ${1:essid}",
    "--ethtool ${1:ethtool}",
    "--gateway ${1:gateway}",
    "--hostname ${1:hostname}",
    "--ip ${1:ip}",
    "--mtu ${1:mtu}",
    "--nameserver ${1:nameserver}",
    "--netmask ${1:netmask}",
    "--nodns",
    "--onboot ${1:onboot}",
    "--wepkey ${1:wepkey}",
    "--notksdevice",
    "--noipv4",
    "--noipv6",
    "--ipv6 ${1:ipv6}",
    "--activate",
    "--nodefroute",
    "--wpakey ${1:wpakey}",
    "--bondslaves ${1:bondslaves}",
    "--bondopts ${1:bondopts}",
    "--vlanid ${1:vlanid}",
    "--ipv6gateway ${1:ipv6gateway}",
    "--teamslaves ${1:teamslaves}",
    "--teamconfig ${1:teamconfig}",
    "--interfacename ${1:interfacename}",
    "--bridgeslaves ${1:bridgeslaves}",
    "--bridgeopts ${1:bridgeopts}",
    "--no-activate",
    "--bindto ${1:mac}",
  ]],
  ["nfs", [
    "--server ${1:hostname}",
    "--dir ${1:dir}",
    "--opts ${1:options}",
  ]],
  ["nvdimm", [
    "reconfigure",
    "use",
    "--namespace ${1:namespace}",
    "--blockdevs ${1:blockdevs}",
    "--mode ${1:mode}",
    "--sectorsize ${1:sectorsize}",
  ]],
  ["ostreesetup", [
    "--osname ${1:osname}",
    "--remote ${1:remote}",
    "--url ${1:url}",
    "--ref ${1:ref}",
    "--nogpg",
  ]],
  ["part", [
    "--asprimary",
    "--fstype ${1:fstype}",
    "--grow",
    "--maxsize ${1:maxsizemb}",
    "--noformat",
    "--onbiosdisk ${1:onbiosdisk}",
    "--ondisk ${1:disk}",
    "--onpart ${1:onpart}",
    "--recommended",
    "--size ${1:size}",
    "--fsoptions ${1:fsopts}",
    "--label ${1:label}",
    "--fsprofile ${1:fsprofile}",
    "--encrypted",
    "--passphrase ${1:passphrase}",
    "--escrowcert ${1:cert_url}",
    "--backuppassphrase",
    "--resize",
    "--hibernation",
    "--cipher ${1:cipher}",
    "--mkfsoptions ${1:mkfsopts}",
    "--luks-version ${1:luks_version}",
    "--pbkdf ${1:pbkdf}",
    "--pbkdf-memory ${1:pbkdf_memory}",
    "--pbkdf-time ${1:pbkdf_time}",
    "--pbkdf-iterations ${1:pbkdf_iterations}",
  ]],
  ["partition", [
    "--asprimary",
    "--fstype ${1:fstype}",
    "--grow",
    "--maxsize ${1:maxsizemb}",
    "--noformat",
    "--onbiosdisk ${1:onbiosdisk}",
    "--ondisk ${1:disk}",
    "--onpart ${1:onpart}",
    "--recommended",
    "--size ${1:size}",
    "--fsoptions ${1:fsopts}",
    "--label ${1:label}",
    "--fsprofile ${1:fsprofile}",
    "--encrypted",
    "--passphrase ${1:passphrase}",
    "--escrowcert ${1:cert_url}",
    "--backuppassphrase",
    "--resize",
    "--hibernation",
    "--cipher ${1:cipher}",
    "--mkfsoptions ${1:mkfsopts}",
    "--luks-version ${1:luks_version}",
    "--pbkdf ${1:pbkdf}",
    "--pbkdf-memory ${1:pbkdf_memory}",
    "--pbkdf-time ${1:pbkdf_time}",
    "--pbkdf-iterations ${1:pbkdf_iterations}",
  ]],
  ["poweroff", [
    "--eject",
    "--kexec",
  ]],
  ["raid", [
    "--device ${1:device}",
    "--fstype ${1:fstype}",
    "--level ${1:level}",
    "--noformat",
    "--spares ${1:spares}",
    "--useexisting",
    "--fsoptions ${1:fsopts}",
    "--fsprofile ${1:fsprofile}",
    "--encrypted",
    "--passphrase ${1:passphrase}",
    "--escrowcert ${1:cert_url}",
    "--backuppassphrase",
    "--label ${1:label}",
    "--cipher ${1:cipher}",
    "--mkfsoptions ${1:mkfsopts}",
    "--chunksize ${1:chunk_size}",
    "--luks-version ${1:luks_version}",
    "--pbkdf ${1:pbkdf}",
    "--pbkdf-memory ${1:pbkdf_memory}",
    "--pbkdf-time ${1:pbkdf_time}",
    "--pbkdf-iterations ${1:pbkdf_iterations}",
  ]],
  ["realm", []],
  ["reboot", [
    "--eject",
    "--kexec",
  ]],
  ["repo", [
    "--name ${1:name}",
    "--baseurl ${1:baseurl}",
    "--mirrorlist ${1:mirrorlist}",
    "--cost ${1:cost}",
    "--excludepkgs ${1:excludepkgs}",
    "--includepkgs ${1:includepkgs}",
    "--proxy ${1:proxy}",
    "--noverifyssl",
    "--install",
    "--metalink ${1:metalink}",
    "--sslcacert ${1:sslcacert}",
    "--sslclientcert ${1:sslclientcert}",
    "--sslclientkey ${1:sslclientkey}",
    "--ignoregroups ${1:ignoregroups}",
  ]],
  ["reqpart", [
    "--add-boot",
  ]],
  ["rescue", [
    "--nomount",
    "--romount",
  ]],
  ["rhsm", [
    "--organization ${1:organization_name}",
    "--activation-key ${1:activation_key}",
    "--connect-to-insights",
    "--proxy PROXY",
    "--server-hostname ${1:subscription_service_server_url}",
    "--rhsm-baseurl ${1:content_base_url}",
  ]],
  ["rootpw", [
    "--iscrypted",
    "--lock",
    "--plaintext",
  ]],
  ["selinux", [
    "--disabled",
    "--enforcing",
    "--permissive",
  ]],
  ["services", [
    "--disabled ${1:list}",
    "--enabled ${1:list}",
  ]],
  ["shutdown", [
    "--eject",
    "--kexec",
  ]],
  ["skipx", []],
  ["snapshot", [
    "--name ${1:name}",
    "--when ${1|post-install,pre-install|}",
  ]],
  ["sshkey", [
    "--username ${1:username}",
  ]],
  ["sshpw", [
    "--username ${1:username}",
    "--iscrypted",
    "--plaintext",
    "--lock",
    "--sshkey",
  ]],
  ["syspurpose", [
    "--role ${1:role_name}",
    "--sla ${1:sla_name}",
    "--usage ${1:usage}",
    "--addon ${1:addon}",
  ]],
  ["text", [
    "--non-interactive",
  ]],
  ["timesource", [
    "--ntp-server ${1:ntp_server}",
    "--ntp-pool ${1:ntp_pool}",
    "--ntp-disable",
    "--nts",
  ]],
  ["timezone", [
    "--utc",
    "--nontp",
    "--ntpservers ${1:ntp_servers}",
  ]],
  ["url", [
    "--proxy ${1:url}",
    "--noverifyssl",
    "--mirrorlist ${1:url}",
    "--url ${1:url}",
    "--metalink ${1:url}",
    "--sslcacert ${1:sslcacert}",
    "--sslclientcert ${1:sslclientcert}",
    "--sslclientkey ${1:sslclientkey}",
  ]],
  ["user", [
    "--homedir ${1:homedir}",
    "--iscrypted",
    "--name ${1:name}",
    "--password ${1:password}",
    "--shell ${1:shell}",
    "--uid ${1:uid}",
    "--lock",
    "--plaintext",
    "--gecos ${1:gecos}",
    "--gid ${1:gid}",
    "--groups ${1:groups}",
  ]],
  ["vnc", [
    "--password ${1:password}",
    "--host ${1:host}",
    "--port ${1:port}",
  ]],
  ["volgroup", [
    "--noformat",
    "--useexisting",
    "--reserved-space ${1:reserved_space}",
    "--reserved-percent ${1:reserved_percent}",
    "--pesize ${1:pesize}",
  ]],
  ["xconfig", [
    "--defaultdesktop ${1|GNOME,KDE|}",
    "--startxonboot",
  ]],
  ["zerombr", []],
  ["zfcp", [
    "--devnum ${1:devnum}",
    "--fcplun ${1:fcplun}",
    "--wwpn ${1:wwpn}",
  ]],
  ["zipl", [
    "--secure-boot",
    "--force-secure-boot",
    "--no-secure-boot"
  ]],
]);
